# Generated by Django 6.0.5 on 2026-05-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_contractedservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractedservice',
            name='delivery_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
