# Generated by Django 6.0.5 on 2026-05-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
